# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  - board: seeeduino_xiao_ble
    shield: totem_left
  - board: seeeduino_xiao_ble
    shield: totem_right
  - board: seeeduino_xiao_ble
    shield: settings_reset
  - board: eyelash_sofle_right
    shield: nice_view_gem
    artifact-name: sofle_right
  - board: eyelash_sofle_left
    shield: nice_view_gem
    snippet: studio-rpc-usb-uart
    artifact-name: sofle_left
  - board: eyelash_sofle_left
    shield: settings_reset
    artifact-name: eyelash_settings_reset
