file_format: "1"
id: sofle
name: Sofle
type: board
arch: arm
url: https://github.com/a741725193/zmk-sofle
features:
  - keys
  - display
  - underglow
outputs:
  - usb
  - ble
siblings:
  - sofle_left//zmk
  - sofle_right//zmk
